---
- name: create test rbd volume
  rbd:
    rbd_name: "volume_{{ item }}"
    pool_name: "{{ rbd_pool }}"
    size: "{{ rbd_volume_size }}"
    feature: "{{ rbd_volume_feature }}"
    state: "present"
  with_items: "{{groups['drivers']}}"
